### ISSUE TITLE
adc_to_mv type conversion problem

### ISSUE THREAD

**Issue by hanuson1** [picotech/picosdk-c-examples#1]
It seems that there is a type conversion problem in function adc_to_mv in ps4000astreaming.cpp. The function is not working properly for negative input data.

**Comment by hsmistry** [comment]
@hanuson1, what sort of data values are you seeing from this function?

**Comment by hanuson1** [comment]
@hsmistry For example:
ChA     8656 =      26mV,       0 =       0mV   
ChA     2513 =       7mV,       0 =       0mV   
ChA     -273 =  131075mV,       0 =       0mV   
ChA    -2148 =  131069mV,       0 =       0mV

**Comment by hsmistry** [comment]
The inputRanges array is an array of _uint32_t_ numbers. The _adc_to_mv()_ and _mv_to_adc()_ functions have been updated to cast the voltage range to an _int32_t_ data type.

Fixed in [changeset 9646720f65ef91196c1c81484b15cb409d1396d0](https://github.com/picotech/picosdk-c-examples/commit/9646720f65ef91196c1c81484b15cb409d1396d0#diff-99f61c622cdb553547f6fb96493eb6a3)

Marking this issue as closed.
